export enum PasswordSetupIntent {
  AUTO_SYNC = "AUTO_SYNC",
  MANUAL_SYNC = "MANUAL_SYNC",
  EXPORT = "export",
  SETUP_ONLY = "SETUP_ONLY",
  EXPORT_FILE_ENCRYPTION = "EXPORT_FILE_ENCRYPTION",
  IMPORT_FILE_DECRYPTION = "IMPORT_FILE_DECRYPTION",
}
