export enum PushEventType {
  SYNC_TRIGGER = "SYNC_TRIGGER",
  LOGOUT = "LOGOUT",
  CLIPBOARD_UNSYNC_ITEM = "CLIPBOARD_UNSYNC_ITEM",
  CLIPBOARD_UNSYNC_ALL = "CLIPBOARD_UNSYNC_ALL",
  MPC_STARTED = "MPC_STARTED",
  MPC_COMPLETED = "MPC_COMPLETED",
}
