export enum UsageEventType {
  STORAGE_READ = "STORAGE_READ",
  STORAGE_WRITE = "STORAGE_WRITE",
  STORAGE_DELETE = "STORAGE_DELETE",
  SYNC_UPLOAD = "SYNC_UPLOAD",
  SYNC_DOWNLOAD = "SYNC_DOWNLOAD",
  PROFILE_SWITCH = "PROFILE_SWITCH",
  BACKUP_CREATE = "BACKUP_CREATE",
  BACKUP_RESTORE = "BACKUP_RESTORE",
}
